SELECT
	TO_CHAR(CURRENT_TIMESTAMP, 'DD-MM-YYYY HH24-MI-SS') AS "DD-MM-YYYY HH24-MI-SS",
	TO_CHAR(CURRENT_TIMESTAMP, 'DD-MM-YYY') AS "DD-MM-YYY",
	TO_CHAR(CURRENT_TIMESTAMP, 'HH24-MI-SS') AS "HH24-MI-SS",
	TO_CHAR(CURRENT_TIMESTAMP, 'DAY') AS "DAY",
	TO_CHAR(CURRENT_TIMESTAMP, 'TZH') AS "TZH";

--|DD-MM-YYYY HH24-MI-SS|DD-MM-YYY|HH24-MI-SS|DAY      |TZH|
--|---------------------|---------|----------|---------|---|
--|07-08-2026 15-37-09  |07-08-026|15-37-09  |FRIDAY   |+07|
