SELECT 
	CONCAT(first_name, ' ', last_name) AS full_name,
	salary,
	RPAD('', DIV(salary, 1000)::INT, '*')
FROM
	employees
WHERE
	COALESCE(salary) > 1200;

--|full_name        |salary|rpad                    |
--|-----------------|------|------------------------|
--|Steven King      |24 000|************************|
--|Neena Kochhar    |17 000|*****************       |
--|Lex De Haan      |17 000|*****************       |
--|Alexander Hunold |9 000 |*********               |
--|Bruce Ernst      |6 000 |******                  |
--|Valli Pataballa  |4 800 |****                    |
--|Diana Lorentz    |4 200 |****                    |
--|Nancy Greenberg  |12 000|************            |
--|Daniel Faviet    |9 000 |*********               |
--|John Chen        |8 200 |********                |
--|Ismael Sciarra   |7 700 |*******                 |
--|Jose Manuel Urman|7 800 |*******                 |
--|Luis Popp        |6 900 |******                  |
--|Alexander Khoo   |3 100 |***                     |
--|Guy Himuro       |2 600 |**                      |
--|Karen Colmenares |2 500 |**                      |
--|Matthew Weiss    |8 000 |********                |
--|Adam Fripp       |8 200 |********                |
--|Payam Kaufling   |7 900 |*******                 |
--|Shanta Vollman   |6 500 |******                  |
--|Kevin Mourgos    |5 800 |*****                   |
--|Steven Markle    |2 200 |**                      |
--|Laura Bissot     |3 300 |***                     |
--|Mozhe Atkinson   |2 800 |**                      |
--|James Marlow     |2 500 |**                      |
--|Jason Mallin     |3 300 |***                     |
--|Michael Rogers   |2 900 |**                      |
--|Ki Gee           |2 400 |**                      |
--|Hazel Philtanker |2 200 |**                      |
--|Renske Ladwig    |3 600 |***                     |
--|Stephen Stiles   |3 200 |***                     |
--|John Seo         |2 700 |**                      |
--|Joshua Patel     |2 500 |**                      |
--|Trenna Rajs      |3 500 |***                     |
--|Curtis Davies    |3 100 |***                     |
--|Randall Matos    |2 600 |**                      |
--|Peter Vargas     |2 500 |**                      |
--|John Russell     |14 000|**************          |
--|Karen Partners   |13 500|*************           |
--|Alberto Errazuriz|12 000|************            |
--|Gerald Cambrault |11 000|***********             |
--|Eleni Zlotkey    |10 500|**********              |
--|Peter Tucker     |10 000|**********              |
--|David Bernstein  |9 500 |*********               |
--|Christopher Olsen|8 000 |********                |
--|Nanette Cambrault|7 500 |*******                 |
--|Oliver Tuvault   |7 000 |*******                 |
--|Janette King     |10 000|**********              |
--|Patrick Sully    |9 500 |*********               |
--|Allan McEwen     |9 000 |*********               |
--|Louise Doran     |7 500 |*******                 |
--|Sarath Sewall    |7 000 |*******                 |
--|Clara Vishney    |10 500|**********              |
--|Danielle Greene  |9 500 |*********               |
--|Mattea Marvins   |7 200 |*******                 |
--|David Lee        |6 800 |******                  |
--|Sundar Ande      |6 400 |******                  |
--|Amit Banda       |6 200 |******                  |
--|Lisa Ozer        |11 500|***********             |
--|Harrison Bloom   |10 000|**********              |
--|Tayler Fox       |9 600 |*********               |
--|William Smith    |7 400 |*******                 |
--|Elizabeth Bates  |7 300 |*******                 |
--|Sundita Kumar    |6 100 |******                  |
--|Den Raphaely     |11 000|***********             |
--|Shelli Baida     |2 900 |**                      |
--|Sigal Tobias     |2 800 |**                      |
--|Ellen Abel       |11 000|***********             |
--|Alyssa Hutton    |8 800 |********                |
--|James Landry     |2 400 |**                      |
--|Jonathon Taylor  |8 600 |********                |
--|Jack Livingston  |8 400 |********                |
--|Kimberely Grant  |7 000 |*******                 |
--|Charles Johnson  |6 200 |******                  |
--|Winston Taylor   |3 200 |***                     |
--|Jean Fleaur      |3 100 |***                     |
--|Martha Sullivan  |2 500 |**                      |
--|Girard Geoni     |2 800 |**                      |
--|Nandita Sarchand |4 200 |****                    |
--|Alexis Bull      |4 100 |****                    |
--|Julia Dellinger  |3 400 |***                     |
--|Anthony Cabrio   |3 000 |***                     |
--|Kelly Chung      |3 800 |***                     |
--|Jennifer Dilly   |3 600 |***                     |
--|Timothy Gates    |2 900 |**                      |
--|Randall Perkins  |2 500 |**                      |
--|Sarah Bell       |4 000 |****                    |
--|Britney Everett  |3 900 |***                     |
--|Samuel McCain    |3 200 |***                     |
--|Vance Jones      |2 800 |**                      |
--|Alana Walsh      |3 100 |***                     |
--|Kevin Feeney     |3 000 |***                     |
--|Donald OConnell  |2 600 |**                      |
--|Douglas Grant    |2 600 |**                      |
--|Jennifer Whalen  |4 400 |****                    |
--|Michael Hartstein|13 000|*************           |
--|Pat Fay          |6 000 |******                  |
--|Susan Mavris     |6 500 |******                  |
--|Hermann Baer     |10 000|**********              |
--|Shelley Higgins  |12 000|************            |
--|William Gietz    |8 300 |********                |
--|DAVID Austin     |4 800 |****                    |
--|Irene Mikkilineni|2 700 |**                      |
